version: "3.7"

volumes:
  mgm1-rondb:
  dn1-rondb:
  dn2-rondb:
  my1-rondb:

networks:
  mynet:
    external: true

services:
  mgm1:
    image: mronstro/rondb:21.04
    networks:
      mynet:
        ipv4_address: 192.168.0.2
    restart: always
    volumes:
      - mgm1-rondb:/var/lib/rondb
    command: [ "ndb_mgmd", "--ndb-nodeid=65", "--initial" ]
  dn1:
    image: mronstro/rondb:21.04
    networks:
      mynet:
        ipv4_address: 192.168.0.4
    restart: always
    depends_on:
      - mgm1
    volumes:
      - dn1-rondb:/var/lib/rondb
    command: [ "ndbmtd", "--ndb-nodeid=1", "--initial" ]
  dn2:
    image: mronstro/rondb:21.04
    networks:
      mynet:
        ipv4_address: 192.168.0.5
    restart: always
    depends_on:
      - mgm1
    volumes:
      - dn2-rondb:/var/lib/rondb
    command: [ "ndbmtd", "--ndb-nodeid=2", "--initial" ]
  my1:
    image: mronstro/rondb:21.04
    networks:
      mynet:
        ipv4_address: 192.168.0.10
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
    depends_on:
      - mgm1
      - dn1
      - dn2
    volumes:
      - my1-rondb:/var/lib/mysql
    command: [ "mysqld", "--ndb-cluster-connection-pool-nodeids=67" ]
